# Generated by Django 2.1.7 on 2019-04-16 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otom', '0003_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=30)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otom.Message')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='reply',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otom.Student'),
        ),
        migrations.AddField(
            model_name='message',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='otom.Student'),
        ),
    ]
